//
//  App.swift
//  Vakta
//
//  Bootstraps a plain `NSApplication` (no storyboard/XIB). The actual .app
//  bundle -- Info.plist, entitlements, icon -- is generated by XcodeGen from
//  `project.yml`; see README.md "Building the .app bundle".
//
//  The window's content view is a raw `NSSplitView`: `SidebarView` (SwiftUI,
//  hosted via `NSHostingView`) on the left, `SessionStore.hostContainer`
//  (plain AppKit, owns every session's live surface) on the right, as
//  direct siblings. SwiftUI therefore never owns, wraps, or is asked to
//  diff the terminal container at all -- see `TerminalContainer.swift` and
//  docs/architecture.md's "Permanent AppKit terminal host" invariant for why
//  that matters.

import AppKit
import Combine
import Metal
import SwiftUI

@main
enum VaktaMain {
    static func main() {
        let app = NSApplication.shared
        let delegate = AppDelegate()
        app.delegate = delegate
        app.setActivationPolicy(.regular)
        app.run()
    }
}

@MainActor
final class AppDelegate: NSObject, NSApplicationDelegate {
    private var window: NSWindow?
    /// The app menu's "New Session" submenu, rebuilt live -- see
    /// `menuNeedsUpdate(_:)`.
    private var newSessionProfilesMenu: NSMenu?
    private var splitView: NSSplitView?
    private var sidebarObserver: AnyCancellable?
    private var sidebarStyleObserver: AnyCancellable?
    /// Constructed in `applicationDidFinishLaunching` once the Application
    /// Support root is resolved (see the guard there) -- never accessed
    /// before that guard passes.
    private var stores: Stores!
    private lazy var preferencesController = PreferencesWindowController(stores: stores)

    // Thin forwarders so the rest of `AppDelegate` reads each store directly.
    private var sessionStore: SessionStore { stores.sessionStore }
    private var keybindingMatcher: KeybindingMatcher { stores.keybindingMatcher }
    private var appearanceStore: AppearanceStore { stores.appearanceStore }
    private var sidebarSettings: SidebarSettingsStore { stores.sidebarSettings }
    private var notificationSettings: NotificationSettingsStore { stores.notificationSettings }
    private var terminalSettings: TerminalSettingsStore { stores.terminalSettings }

    /// The AppKit sidebar/terminal chrome whose colors follow the terminal
    /// theme; re-applied when it changes (SwiftUI parts update themselves).
    private var sidebarContainerView: NSView?
    private var terminalWrapperView: NSView?
    private var sidebarHostView: NSView?
    private var terminalColorObserver: AnyCancellable?

    /// Menu-bar status item summarizing agent activity across all sessions, and
    /// the subscription that keeps its icon live.
    private var statusItem: NSStatusItem?
    private var agentStatusObserver: AnyCancellable?
    private var passthroughObserver: AnyCancellable?

    /// The ⌘K session switcher's floating panel and its backing state.
    private var switcherPanel: SessionSwitcherPanel?
    private let switcherModel = SessionSwitcherModel()

    /// Sidebar widths: a full panel, and a narrow icon rail when collapsed.
    private let expandedSidebarWidth: CGFloat = 220
    private let collapsedSidebarWidth: CGFloat = 56

    /// Titlebar band reserved at the top of both panes (matches
    /// `SidebarView`'s own inset) so the traffic lights never overlap live
    /// content -- see `makeWindow`.
    private let titlebarInset: CGFloat = 28

    func applicationDidFinishLaunching(_: Notification) {
        // Kicked off first, before any other launch work: resolving the
        // login-shell PATH runs a real shell + rc files on a background
        // thread (see `ResolvedPATH`), so starting it here -- rather than
        // where `SessionStore` used to call `ShellEnvironment.resolvedPATH()`
        // directly, synchronously, on the main actor -- gives it the
        // longest possible head start against everything else below before
        // `Stores.init` needs the result.
        let resolvedPATH = ResolvedPATH()

        // libghostty renders every surface with Metal and dereferences its
        // rendering context without a nil check, so `ghostty_surface_new`
        // segfaults when there is no usable GPU/window-server context. That
        // happens when Vakta is launched from an SSH session or otherwise with
        // no logged-in desktop session: on Apple Silicon a Metal *device* may
        // still exist, but with no WindowServer connection there are no
        // screens and no drawable. Guard on both and fail with a clear message
        // instead of crashing deep in the C library.
        guard !NSScreen.screens.isEmpty, MTLCreateSystemDefaultDevice() != nil else {
            presentFatalAlert(
                "No display session",
                "Vakta renders its terminals with Metal and needs a logged-in "
                    + "desktop session. This usually means it was launched over "
                    + "SSH or remotely with no active display. Run it from the "
                    + "Mac's own screen instead."
            )
            NSApp.terminate(nil)
            return
        }

        // Resolve the persisted-settings root once, before any store reads
        // or writes anything. `ApplicationSupportRoot.resolve()` throws
        // rather than silently falling back to the temp directory (where an
        // OS wipe would make every "saved" setting vanish); this is that
        // failure's one handler, in the same "can't run, say why, exit"
        // shape as the display-session guard above.
        let root: URL
        do {
            root = try ApplicationSupportRoot.resolve()
        } catch {
            presentFatalAlert(
                "Can't access Application Support",
                "Vakta stores your settings, profiles, and sessions in "
                    + "~/Library/Application Support/Vakta, and couldn't "
                    + "reach it: \(error.localizedDescription)"
            )
            NSApp.terminate(nil)
            return
        }
        stores = Stores(root: root, resolvedPATH: resolvedPATH)

        // Apply the saved UI-chrome appearance before the window appears, so
        // it doesn't flash the system theme first.
        appearanceStore.apply()

        buildMainMenu()

        let window = makeWindow()
        self.window = window
        window.makeKeyAndOrderFront(nil)
        NSApp.activate(ignoringOtherApps: true)

        // The initial session (created inside `SessionStore.init()`, before
        // this window -- and therefore `hostContainer` -- existed) already
        // asked to be selected and focused; that request's `makeFirstResponder`
        // call silently found `hostContainer.window == nil` and did nothing.
        // Re-issue it now that the container is actually in a window.
        if let id = sessionStore.selectedID {
            sessionStore.hostContainer.select(id)
        }

        keybindingMatcher.install { [weak self] action in
            guard let self else { return }
            switch action {
            case .selectSession(let index): self.sessionStore.selectSession(at: index)
            case .toggleSidebar: self.sessionStore.toggleSidebar()
            case .openPreferences: self.preferencesController.show()
            case .openSessionSwitcher: self.showSessionSwitcher()
            case .quit: NSApp.terminate(nil)
            }
        }

        // Finish wiring the attention notifier now that the app is up: give it
        // the user's preferences, a way to surface a session on click, and
        // (in the packaged app) notification authorization.
        sessionStore.notifier.settings = notificationSettings
        sessionStore.notifier.onActivateSession = { [weak self] id in
            self?.activateSession(id)
        }
        sessionStore.notifier.requestAuthorization()

        setUpStatusItem()

        // When the terminal theme changes, re-tint the AppKit chrome (the
        // SwiftUI sidebar re-reads the published colors on its own).
        terminalColorObserver = sessionStore.$terminalBackgroundColor
            .sink { [weak self] color in self?.applyTerminalChromeColor(color) }

        // Drive the sidebar width off the store's collapsed flag, which the
        // sidebar's own button and the View menu both toggle.
        sidebarObserver = sessionStore.$sidebarCollapsed.sink { [weak self] collapsed in
            guard let self else { return }
            self.applySidebarWidth(collapsed: collapsed, style: self.sidebarSettings.collapseStyle)
        }

        // Re-apply the width when the collapse *style* changes (icons vs.
        // hidden), so flipping the preference while collapsed updates live.
        // Uses the emitted `style` directly, NOT `sidebarSettings.collapseStyle`
        // -- `@Published`'s publisher fires from `willSet`, so a synchronous
        // re-read here would still see the OLD value (see
        // `SidebarWidthPlanner`'s doc comment).
        sidebarStyleObserver = sidebarSettings.$collapseStyle.sink { [weak self] style in
            guard let self else { return }
            self.applySidebarWidth(collapsed: self.sessionStore.sidebarCollapsed, style: style)
        }
    }

    func applicationShouldTerminateAfterLastWindowClosed(_: NSApplication) -> Bool {
        true
    }

    func applicationDidBecomeActive(_: Notification) {
        // `stores` is nil until partway through `applicationDidFinishLaunching`
        // (it needs the display-session and Application Support guards to
        // pass first) -- showing either guard's modal fatal alert can itself
        // trigger this callback, before `stores` exists.
        guard stores != nil else { return }
        // Keep the "Attach existing" list fresh when returning to the app.
        sessionStore.refreshDiscovery()
    }

    /// Moves the divider between the full panel and the icon rail. Done without
    /// implicit animation: animating `setPosition` (especially with a nested
    /// `layoutSubtreeIfNeeded`) leaves a stale divider streak. We force a clean
    /// full redraw instead. `style` is always the caller's own current/emitted
    /// value (see `SidebarWidthPlanner`'s doc comment for why this can't just
    /// re-read `sidebarSettings.collapseStyle` from every call site).
    private func applySidebarWidth(collapsed: Bool, style: SidebarCollapseStyle) {
        guard let splitView else { return }
        let target = SidebarWidthPlanner.width(
            collapsed: collapsed,
            style: style,
            collapsedWidth: collapsedSidebarWidth,
            expandedWidth: expandedSidebarWidth
        )
        splitView.setPosition(target, ofDividerAt: 0)
        splitView.layoutSubtreeIfNeeded()
        splitView.needsDisplay = true
        splitView.window?.viewsNeedDisplay = true
    }

    @objc private func toggleSidebar() {
        sessionStore.toggleSidebar()
    }

    /// Re-applies the terminal theme's background to the AppKit sidebar/terminal
    /// chrome, and flips the sidebar's appearance to keep its text legible.
    private func applyTerminalChromeColor(_ color: NSColor) {
        sidebarContainerView?.layer?.backgroundColor = color.cgColor
        terminalWrapperView?.layer?.backgroundColor = color.cgColor
        sidebarHostView?.appearance = NSAppearance(named: color.isDark ? .darkAqua : .aqua)
    }

    @objc private func showPreferences() {
        preferencesController.show()
    }

    private func makeWindow() -> NSWindow {
        let split = SeamlessSplitView()
        split.isVertical = true
        split.dividerStyle = .thin

        // The sidebar paints itself the terminal theme's background color, so
        // it and the opaque terminal read as one continuous surface (the hidden
        // divider completes the seam). A solid color -- not vibrancy -- because
        // the goal is to *match* the terminal, which a translucent material
        // can't do. The hosting view's appearance is forced to match the
        // background's darkness so SwiftUI text/selection stay legible whatever
        // the app's chrome appearance is set to.
        let sidebarHost = NSHostingView(
            rootView: SidebarView()
                .environmentStores(stores)
        )
        sidebarHost.appearance = NSAppearance(
            named: sessionStore.terminalBackgroundColor.isDark ? .darkAqua : .aqua
        )
        sidebarHostView = sidebarHost

        let sidebarContainer = NSView()
        sidebarContainer.wantsLayer = true
        sidebarContainer.layer?.backgroundColor = sessionStore.terminalBackgroundColor.cgColor
        sidebarContainer.frame = NSRect(x: 0, y: 0, width: expandedSidebarWidth, height: 640)
        sidebarContainerView = sidebarContainer
        // Frame + autoresizing, NOT Auto Layout: the split view drives the
        // container's frame imperatively (`setPosition` on collapse), and the
        // host autoresizes to fill it. Pinning the host with constraints fought
        // that frame-based sizing and hung the collapse layout pass.
        sidebarHost.frame = sidebarContainer.bounds
        sidebarHost.autoresizingMask = [.width, .height]
        sidebarContainer.addSubview(sidebarHost)

        // Reserve the titlebar band on the terminal side too. With
        // `fullSizeContentView` the content spans under the titlebar, so the
        // terminal is inset down by the titlebar height and backed with the
        // same dark color. That keeps the traffic lights over an empty dark
        // band in every sidebar state -- expanded, icon rail, or hidden --
        // instead of on top of live terminal content. The host container stays
        // a permanent AppKit subview (docs/architecture.md, "Permanent AppKit
        // terminal host"); wrapping it in a plain inset view doesn't touch
        // any surface.
        let terminalContainer = sessionStore.hostContainer
        let terminalWrapper = NSView()
        terminalWrapper.wantsLayer = true
        terminalWrapper.layer?.backgroundColor = sessionStore.terminalBackgroundColor.cgColor
        terminalWrapper.frame = NSRect(x: 0, y: 0, width: 860, height: 640)
        terminalWrapperView = terminalWrapper
        // A small left gap (filled by the wrapper's dark background) gives the
        // terminal content breathing room from the sidebar -- a bit of a spacer.
        let terminalGap: CGFloat = 8
        terminalContainer.frame = NSRect(
            x: terminalGap, y: 0,
            width: 860 - terminalGap, height: 640 - titlebarInset
        )
        // Flexible width/height; fixed left gap, top band, and bottom.
        terminalContainer.autoresizingMask = [.width, .height]
        terminalWrapper.addSubview(terminalContainer)

        split.addArrangedSubview(sidebarContainer)
        split.addArrangedSubview(terminalWrapper)
        // Sidebar keeps its width when the window resizes; the terminal flexes.
        split.setHoldingPriority(.defaultHigh, forSubviewAt: 0)
        self.splitView = split

        let window = NSWindow(
            contentRect: NSRect(x: 0, y: 0, width: 1080, height: 640),
            styleMask: [.titled, .closable, .miniaturizable, .resizable, .fullSizeContentView],
            backing: .buffered,
            defer: false
        )
        window.title = "Vakta"
        // Full-height sidebar: the content view (the split view) spans the whole
        // window, including behind the titlebar, so the sidebar's vibrancy runs
        // all the way to the top with the traffic lights floating over it --
        // like Mail/Finder. The sidebar insets its own header below the traffic
        // lights (see `SidebarView`). No opaque titlebar strip, no title text.
        window.titlebarAppearsTransparent = true
        window.titleVisibility = .hidden
        window.contentView = split
        window.center()
        // `AppDelegate` (this object) holds `window` with a strong Swift
        // reference; AppKit's default `isReleasedWhenClosed = true` would
        // additionally release it when the user closes it, over-releasing
        // and crashing on next access (e.g. on quit).
        window.isReleasedWhenClosed = false
        return window
    }

    /// Settled design decision #5: the menu bar is deliberately free of
    /// every `keyEquivalent`. Any `⌘`-based key equivalent set here would
    /// let AppKit's menu system swallow the keystroke before it ever reaches
    /// the responder chain -- before even `KeybindingMatcher`'s local
    /// monitor gets a look, per Apple's documented event dispatch order.
    /// herdr (and Vakta's own chord) must see every key; menu items here are
    /// mouse/trackpad-only by design.
    private func buildMainMenu() {
        let mainMenu = NSMenu()

        let appMenuItem = NSMenuItem()
        let appMenu = NSMenu()
        appMenu.addItem(withTitle: "About Vakta", action: nil, keyEquivalent: "")
        appMenu.addItem(.separator())
        // No ⌘ key equivalent: docs/architecture.md's "Keybindings routed through
        // the matcher, not menu key equivalents" invariant keeps every menu
        // item keyless so keystrokes reach herdr. Preferences is reachable by
        // mouse here, and the user can bind it (and Toggle Sidebar) to a chord
        // inside the pane -- that goes through `KeybindingMatcher`, which by
        // design sees keys before the menu ever could.
        let preferencesItem = NSMenuItem(
            title: "Preferences…",
            action: #selector(showPreferences),
            keyEquivalent: ""
        )
        preferencesItem.target = self
        appMenu.addItem(preferencesItem)
        appMenu.addItem(.separator())
        let quitItem = NSMenuItem(
            title: "Quit Vakta",
            action: #selector(NSApplication.terminate(_:)),
            keyEquivalent: ""
        )
        quitItem.target = NSApp
        appMenu.addItem(quitItem)
        appMenuItem.submenu = appMenu
        mainMenu.addItem(appMenuItem)

        let sessionMenuItem = NSMenuItem()
        let sessionMenu = NSMenu(title: "Session")

        // "New Session" is a submenu of profiles; its first item (the default
        // profile) doubles as the plain "new session" action. Rebuilt from
        // current `sessionStore.profiles` every time it's about to open
        // (`menuNeedsUpdate(_:)` below) rather than once here at launch --
        // editing/deleting a profile must be reflected immediately, and a
        // stale item must not be able to launch a deleted profile or an
        // obsolete command snapshot (hence `representedObject` holding only
        // the profile's stable id, resolved back to a live `Profile` at
        // click time in `newSessionFromProfile`).
        let newSessionItem = NSMenuItem(title: "New Session", action: nil, keyEquivalent: "")
        let profilesMenu = NSMenu(title: "New Session")
        profilesMenu.delegate = self
        newSessionProfilesMenu = profilesMenu
        newSessionItem.submenu = profilesMenu
        sessionMenu.addItem(newSessionItem)

        // Session switcher (⌘K by default, bound via KeybindingMatcher). No
        // keyEquivalent here -- see docs/architecture.md's "Keybindings routed
        // through the matcher, not menu key equivalents" invariant; the chord
        // is handled earlier.
        sessionMenu.addItem(.separator())
        let switcherItem = NSMenuItem(
            title: "Switch Session…",
            action: #selector(showSessionSwitcherFromMenu),
            keyEquivalent: ""
        )
        switcherItem.target = self
        sessionMenu.addItem(switcherItem)

        sessionMenuItem.submenu = sessionMenu
        mainMenu.addItem(sessionMenuItem)

        let viewMenuItem = NSMenuItem()
        let viewMenu = NSMenu(title: "View")
        // No key equivalent, to keep every keystroke flowing to the terminal
        // (docs/architecture.md's "Keybindings routed through the matcher, not menu
        // key equivalents" invariant). The sidebar's own button and the
        // Ctrl+Shift+num chords are the keyboard-free / rebindable paths.
        let toggleItem = NSMenuItem(
            title: "Toggle Sidebar",
            action: #selector(toggleSidebar),
            keyEquivalent: ""
        )
        toggleItem.target = self
        viewMenu.addItem(toggleItem)
        viewMenuItem.submenu = viewMenu
        mainMenu.addItem(viewMenuItem)

        NSApp.mainMenu = mainMenu
    }

    private func presentFatalAlert(_ title: String, _ message: String) {
        let alert = NSAlert()
        alert.messageText = title
        alert.informativeText = message
        alert.alertStyle = .critical
        alert.runModal()
    }

    @objc private func newSessionFromProfile(_ sender: NSMenuItem) {
        // Resolved by id against CURRENT profiles, never a value captured
        // when the menu was built -- the profile may have been edited (a
        // stale snapshot would launch the old command) or deleted (a stale
        // id must fall back to the default rather than launching nothing or
        // crashing) since the menu last opened.
        guard let id = sender.representedObject as? Profile.ID,
              let profile = sessionStore.profiles.first(where: { $0.id == id })
        else {
            sessionStore.createSession()
            return
        }
        sessionStore.createSession(profile: profile)
    }

    // MARK: Menu-bar status item

    /// Creates the menu-bar extra and keeps its icon in sync with agent status.
    /// The dropdown itself is (re)built lazily in `menuNeedsUpdate(_:)`.
    private func setUpStatusItem() {
        let item = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
        item.button?.imagePosition = .imageLeading
        let menu = NSMenu()
        menu.delegate = self
        item.menu = menu
        statusItem = item
        updateStatusItemButton(sessionStore.agentStatus)

        // `@Published` fires before the stored value updates, so read the
        // emitted value rather than `sessionStore.agentStatus`.
        agentStatusObserver = sessionStore.$agentStatus.sink { [weak self] status in
            self?.updateStatusItemButton(status)
        }
        // Reflect passthrough mode in the menu-bar item too.
        passthroughObserver = keybindingMatcher.$passthrough.sink { [weak self] _ in
            guard let self else { return }
            self.updateStatusItemButton(self.sessionStore.agentStatus)
        }
    }

    /// Icon reflects the busiest state across sessions; a count trails it when
    /// any session is waiting on the user.
    private func updateStatusItemButton(_ status: [Session.ID: AgentStatus]) {
        guard let button = statusItem?.button else { return }

        // Passthrough mode takes over the indicator while it's active.
        if keybindingMatcher.passthrough {
            let image = NSImage(systemSymbolName: "keyboard.fill", accessibilityDescription: "Passthrough mode on")
            image?.isTemplate = true
            button.image = image
            button.title = " raw"
            button.toolTip = "Passthrough on — keys go straight to the session. Double-tap the modifier to exit."
            return
        }
        button.toolTip = nil

        let waiting = status.values.filter { $0 == .attention }.count
        let working = status.values.filter { $0 == .working }.count

        // Symbols chosen from the macOS 11 set so they resolve on the 13.0
        // deployment target (a missing symbol renders no icon at all).
        let symbol: String
        if waiting > 0 {
            symbol = "exclamationmark.circle.fill"
        } else if working > 0 {
            symbol = "ellipsis.circle"
        } else {
            symbol = "terminal"
        }
        let image = NSImage(systemSymbolName: symbol, accessibilityDescription: "Vakta agent status")
        image?.isTemplate = true
        button.image = image
        button.title = waiting > 0 ? " \(waiting)" : ""
    }

    /// A small filled dot in the session's status color, for menu-bar rows
    /// (non-template so the color shows, unlike the monochrome button icon).
    private func statusDotImage(_ status: AgentStatus) -> NSImage {
        let color: NSColor
        switch status {
        case .working: color = .systemOrange
        case .attention: color = .systemYellow
        case .idle: color = .systemGreen
        case .none, .unavailable: color = .tertiaryLabelColor
        }
        let size = NSSize(width: 10, height: 10)
        let image = NSImage(size: size)
        image.lockFocus()
        color.setFill()
        NSBezierPath(ovalIn: NSRect(origin: .zero, size: size)).fill()
        image.unlockFocus()
        image.isTemplate = false
        return image
    }

    @objc private func menuBarSelectSession(_ sender: NSMenuItem) {
        guard let id = sender.representedObject as? UUID else { return }
        activateSession(id)
    }

    @objc private func showMainWindow() {
        window?.makeKeyAndOrderFront(nil)
        NSApp.activate(ignoringOtherApps: true)
    }

    /// Selects a session and brings Vakta to the front -- shared by the
    /// menu-bar rows and notification taps.
    private func activateSession(_ id: Session.ID) {
        sessionStore.select(id)
        window?.makeKeyAndOrderFront(nil)
        NSApp.activate(ignoringOtherApps: true)
    }

    // MARK: Session switcher (⌘K)

    @objc private func showSessionSwitcherFromMenu() {
        showSessionSwitcher()
    }

    /// Opens (or refocuses) the command-palette session switcher.
    private func showSessionSwitcher() {
        // Snapshot the current sessions for the palette.
        switcherModel.reset(items: sessionStore.sessions.map { session in
            SessionSwitcherItem(
                id: session.id,
                title: session.displayTitle,
                status: sessionStore.agentStatus[session.id] ?? .none
            )
        })
        switcherModel.onSelect = { [weak self] id in self?.selectFromSwitcher(id) }
        switcherModel.onCancel = { [weak self] in self?.closeSwitcher() }

        if let panel = switcherPanel {
            panel.center()
            panel.makeKeyAndOrderFront(nil)
            NSApp.activate(ignoringOtherApps: true)
            return
        }

        let host = NSHostingView(
            rootView: SessionSwitcherView(
                model: switcherModel,
                highlightColor: Color(nsColor: sessionStore.terminalSelectionColor)
            )
        )
        let panel = SessionSwitcherPanel(
            contentRect: NSRect(x: 0, y: 0, width: 440, height: 360),
            styleMask: [.titled, .fullSizeContentView],
            backing: .buffered,
            defer: false
        )
        panel.model = switcherModel
        panel.titleVisibility = .hidden
        panel.titlebarAppearsTransparent = true
        panel.isMovableByWindowBackground = true
        panel.isFloatingPanel = true
        panel.level = .floating
        // Dismissal is handled by `windowDidResignKey` (covers ⌘-Tab away and
        // clicking elsewhere). We deliberately do NOT also set
        // `hidesOnDeactivate`, which can re-order the panel back in on
        // reactivation and fight the delegate.
        panel.animationBehavior = .utilityWindow
        panel.contentView = host
        panel.delegate = self
        // Held strongly here; stop AppKit additionally releasing on close.
        panel.isReleasedWhenClosed = false
        switcherPanel = panel

        panel.center()
        panel.makeKeyAndOrderFront(nil)
        NSApp.activate(ignoringOtherApps: true)
    }

    private func selectFromSwitcher(_ id: Session.ID) {
        switcherPanel?.orderOut(nil)
        activateSession(id)
    }

    private func closeSwitcher() {
        switcherPanel?.orderOut(nil)
        window?.makeKeyAndOrderFront(nil)
    }
}

// MARK: - Menu-bar dropdown

extension AppDelegate: NSMenuDelegate {
    /// Rebuilt on each open so session rows and their status dots are
    /// current. Also handles the app menu's "New Session" submenu -- see
    /// its construction comment in `buildMainMenu` -- so editing/deleting a
    /// profile is reflected the next time either menu opens, not just in
    /// the (already-live, SwiftUI-driven) sidebar menu.
    func menuNeedsUpdate(_ menu: NSMenu) {
        if menu === newSessionProfilesMenu {
            menu.removeAllItems()
            for entry in ProfileMenuPlanner.entries(for: sessionStore.profiles) {
                let item = NSMenuItem(title: entry.title, action: #selector(newSessionFromProfile(_:)), keyEquivalent: "")
                item.target = self
                item.representedObject = entry.profileID
                menu.addItem(item)
            }
            return
        }
        guard menu === statusItem?.menu else { return }
        menu.removeAllItems()

        let sessions = sessionStore.sessions
        let waiting = sessionStore.agentStatus.values.filter { $0 == .attention }.count
        let summary = sessions.isEmpty
            ? "No sessions"
            : "\(sessions.count) session\(sessions.count == 1 ? "" : "s") · \(waiting) waiting"
        let header = NSMenuItem(title: summary, action: nil, keyEquivalent: "")
        header.isEnabled = false
        menu.addItem(header)
        menu.addItem(.separator())

        for session in sessions {
            let status = sessionStore.agentStatus[session.id] ?? .none
            let item = NSMenuItem(
                title: session.displayTitle,
                action: #selector(menuBarSelectSession(_:)),
                keyEquivalent: ""
            )
            item.target = self
            item.representedObject = session.id
            item.image = statusDotImage(status)
            item.state = (session.id == sessionStore.selectedID) ? .on : .off
            menu.addItem(item)
        }

        menu.addItem(.separator())
        let show = NSMenuItem(title: "Show Vakta", action: #selector(showMainWindow), keyEquivalent: "")
        show.target = self
        menu.addItem(show)
        let quit = NSMenuItem(title: "Quit Vakta", action: #selector(NSApplication.terminate(_:)), keyEquivalent: "")
        quit.target = NSApp
        menu.addItem(quit)
    }
}

// MARK: - Seamless split view

/// An `NSSplitView` that keeps a real, draggable divider (so the sidebar can
/// still be resized by dragging and collapsed via `setPosition`) but paints no
/// line, so the sidebar's vibrancy meets the opaque terminal with no visible
/// seam. Only the *drawing* is suppressed -- thickness and hit-testing are the
/// stock `.thin` behavior.
private final class SeamlessSplitView: NSSplitView {
    // A faint hairline instead of the stock heavy line: enough to separate the
    // sidebar from the same-colored terminal without a harsh black divider.
    // The top titlebar band is left unpainted so the hairline never crosses the
    // traffic lights -- when the sidebar collapses to the icon rail (narrower
    // than the traffic-light cluster) the divider otherwise cuts through them.
    override func drawDivider(in rect: NSRect) {
        let titlebarBand: CGFloat = 28 // matches SidebarView/AppDelegate inset
        // Non-flipped coords (origin bottom-left): trim the height so the top
        // band stays clear.
        var painted = rect
        painted.size.height = max(0, rect.height - titlebarBand)
        NSColor.white.withAlphaComponent(0.08).setFill()
        painted.fill()
    }
}

// MARK: - Session switcher panel lifecycle

extension AppDelegate: NSWindowDelegate {
    /// Dismiss the switcher when it loses key focus (click elsewhere), so it
    /// behaves like a proper command palette.
    func windowDidResignKey(_ notification: Notification) {
        guard let window = notification.object as? NSWindow, window === switcherPanel else { return }
        switcherPanel?.orderOut(nil)
    }
}
