//
//  App.swift
//  Vakta
//
//  Bootstraps a plain `NSApplication` (no storyboard/XIB). The actual .app
//  bundle -- Info.plist, entitlements, icon -- is generated by XcodeGen from
//  `project.yml`; see README.md "Building the .app bundle".
//
//  The window's content view is a raw `NSSplitView`: `SidebarView` (SwiftUI,
//  hosted via `NSHostingView`) on the left, `SessionStore.hostContainer`
//  (plain AppKit, owns every session's live surface) on the right, as
//  direct siblings. SwiftUI therefore never owns, wraps, or is asked to
//  diff the terminal container at all -- see `TerminalContainer.swift` and
//  docs/architecture.md's "Permanent AppKit terminal host" invariant for why
//  that matters.

import AppKit
import Combine
import Metal
import SwiftUI

@main
enum VaktaMain {
    static func main() {
        let app = NSApplication.shared
        let delegate = AppDelegate()
        app.delegate = delegate
        app.setActivationPolicy(.regular)
        app.run()
    }
}

@MainActor
final class AppDelegate: NSObject, NSApplicationDelegate {
    private var window: NSWindow?
    /// The app menu's "New Session" submenu, rebuilt live -- see
    /// `menuNeedsUpdate(_:)`.
    private var newSessionProfilesMenu: NSMenu?
    private var splitView: NSSplitView?
    private var sidebarObserver: AnyCancellable?
    private var sidebarStyleObserver: AnyCancellable?
    /// Constructed in `applicationDidFinishLaunching` once the Application
    /// Support root is resolved (see the guard there) -- never accessed
    /// before that guard passes.
    private var stores: Stores!
    private lazy var preferencesController = PreferencesWindowController(stores: stores)
    private lazy var onboardingController = OnboardingWindowController(parentWindowProvider: { [weak self] in self?.window })
    /// The tour's herdr/tmux install step. Checks the same resolved PATH
    /// sessions get; Install opens a transient session running the command.
    private lazy var multiplexerSetup = MultiplexerSetupModel(
        pathProvider: { [weak self] in self?.sessionStore.resolvedPATH ?? ShellEnvironment.fallbackPATH() },
        install: { [weak self] tool, command in
            guard let self else { return }
            let profile = MultiplexerSetupPlanner.installerProfile(for: tool, installCommand: command, id: UUID())
            self.sessionStore.createSession(profile: profile, isTransient: true)
        }
    )

    // Thin forwarders so the rest of `AppDelegate` reads each store directly.
    private var sessionStore: SessionStore { stores.sessionStore }
    private var keybindingMatcher: KeybindingMatcher { stores.keybindingMatcher }
    private var appearanceStore: AppearanceStore { stores.appearanceStore }
    private var sidebarSettings: SidebarSettingsStore { stores.sidebarSettings }
    private var notificationSettings: NotificationSettingsStore { stores.notificationSettings }
    private var terminalSettings: TerminalSettingsStore { stores.terminalSettings }
    private var workspaceRefreshMonitor: WorkspaceRefreshMonitor { stores.workspaceRefreshMonitor }
    private var editorPreferences: EditorPreferencesStore { stores.editorPreferences }
    private var fileSidebarPreferences: FileSidebarPreferencesStore { stores.fileSidebarPreferences }

    /// The AppKit sidebar/terminal chrome whose colors follow the terminal
    /// theme; re-applied when it changes (SwiftUI parts update themselves).
    private var sidebarContainerView: NSView?
    private var terminalWrapperView: NSView?
    private var sidebarHostView: NSView?
    private var terminalColorObserver: AnyCancellable?

    /// The right-hand file sidebar pane (a third `NSSplitView` arranged
    /// subview) and the subscription that shows/hides it on the preference.
    private var fileSidebarContainerView: NSView?
    private var fileSidebarHostView: NSView?
    private var fileSidebarObserver: AnyCancellable?

    /// Menu-bar status item summarizing agent activity across all sessions, and
    /// the subscription that keeps its icon live.
    private var statusItem: NSStatusItem?
    private var agentStatusObserver: AnyCancellable?
    private var passthroughObserver: AnyCancellable?

    /// The ⌘K command palette's floating panel and its backing state. The
    /// host is kept typed (not just `panel.contentView`) so its `rootView`'s
    /// theme colors can be refreshed on reuse -- see `showSessionSwitcher`.
    private var switcherPanel: SessionSwitcherPanel?
    /// The which-key overlay for leader sequences (see `LeaderHintOverlay`).
    private var leaderOverlay: LeaderHintOverlay?
    private var leaderBeginObserver: AnyCancellable?
    private var switcherHostView: NSHostingView<SessionSwitcherView>?
    private let switcherModel = SessionSwitcherModel()
    /// Sessions whose workspaces were queried for the currently-open palette
    /// but haven't reported back yet; drained (and the observer torn down)
    /// as each arrives -- see `showSessionSwitcher`.
    private var pendingPaletteWorkspaceFetches: Set<Session.ID> = []
    private var globalPaneFetchGeneration: Int?
    private var workspacesObserver: AnyCancellable?
    private var panesObserver: AnyCancellable?

    /// Sidebar widths: a narrow icon rail when collapsed, and the expanded
    /// panel's draggable bounds. The expanded width itself is persisted in
    /// `SidebarSettingsStore` (defaulting to `SidebarSettings.defaultExpandedWidth`)
    /// and clamped to these bounds wherever it's applied or captured.
    private let collapsedSidebarWidth: CGFloat = 56
    private let minimumExpandedSidebarWidth: CGFloat = 160
    private let maximumExpandedSidebarWidth: CGFloat = 480

    /// The persisted expanded width, clamped to the draggable bounds so a
    /// stray saved value (see `SidebarSettings`' "clamp at use" note) can never
    /// place the divider off-screen or under the rail.
    private func resolvedExpandedWidth() -> CGFloat {
        let saved = sidebarSettings.expandedWidth
        guard saved.isFinite else { return SidebarSettings.defaultExpandedWidth }
        return min(max(saved, minimumExpandedSidebarWidth), maximumExpandedSidebarWidth)
    }

    /// Titlebar band reserved at the top of both panes (matches
    /// `SidebarView`'s own inset) so the traffic lights never overlap live
    /// content -- see `makeWindow`.
    private let titlebarInset: CGFloat = 28

    func applicationDidFinishLaunching(_: Notification) {
        // Kicked off first, before any other launch work: resolving the
        // login-shell PATH runs a real shell + rc files on a background
        // thread (see `ResolvedPATH`), so starting it here -- rather than
        // where `SessionStore` used to call `ShellEnvironment.resolvedPATH()`
        // directly, synchronously, on the main actor -- gives it the
        // longest possible head start against everything else below before
        // `Stores.init` needs the result.
        let resolvedPATH = ResolvedPATH()

        // libghostty renders every surface with Metal and dereferences its
        // rendering context without a nil check, so `ghostty_surface_new`
        // segfaults when there is no usable GPU/window-server context. That
        // happens when Vakta is launched from an SSH session or otherwise with
        // no logged-in desktop session: on Apple Silicon a Metal *device* may
        // still exist, but with no WindowServer connection there are no
        // screens and no drawable. Guard on both and fail with a clear message
        // instead of crashing deep in the C library.
        guard !NSScreen.screens.isEmpty, MTLCreateSystemDefaultDevice() != nil else {
            presentFatalAlert(
                "No display session",
                "Vakta renders its terminals with Metal and needs a logged-in "
                    + "desktop session. This usually means it was launched over "
                    + "SSH or remotely with no active display. Run it from the "
                    + "Mac's own screen instead."
            )
            NSApp.terminate(nil)
            return
        }

        // Resolve the persisted-settings root once, before any store reads
        // or writes anything. `ApplicationSupportRoot.resolve()` throws
        // rather than silently falling back to the temp directory (where an
        // OS wipe would make every "saved" setting vanish); this is that
        // failure's one handler, in the same "can't run, say why, exit"
        // shape as the display-session guard above.
        let root: URL
        do {
            root = try ApplicationSupportRoot.resolve()
        } catch {
            presentFatalAlert(
                "Can't access Application Support",
                "Vakta stores your settings, profiles, and sessions in "
                    + "~/Library/Application Support/Vakta, and couldn't "
                    + "reach it: \(error.localizedDescription)"
            )
            NSApp.terminate(nil)
            return
        }
        // Before `Stores` seeds its default files: onboarding tells a fresh
        // install from an upgrade by whether any settings file already exists.
        let onboarding = OnboardingLaunch.evaluate(
            root: root,
            currentVersion: OnboardingLaunch.bundleVersion,
            releaseNotes: WhatsNewCatalog.releaseNotes
        )
        stores = Stores(root: root, resolvedPATH: resolvedPATH)

        // Apply the saved UI-chrome appearance before the window appears, so
        // it doesn't flash the system theme first.
        appearanceStore.apply()

        buildMainMenu()

        let window = makeWindow()
        self.window = window
        window.makeKeyAndOrderFront(nil)
        NSApp.activate(ignoringOtherApps: true)

        // The initial session (created inside `SessionStore.init()`, before
        // this window -- and therefore `hostContainer` -- existed) already
        // asked to be selected and focused; that request's `makeFirstResponder`
        // call silently found `hostContainer.window == nil` and did nothing.
        // Re-issue it now that the container is actually in a window.
        if let id = sessionStore.selectedID {
            sessionStore.hostContainer.select(id)
        }

        keybindingMatcher.commandContextProvider = { [weak self] in
            self?.currentCommandContext() ?? .empty
        }
        keybindingMatcher.install { [weak self] command in
            self?.perform(command)
        }
        let overlay = LeaderHintOverlay(
            matcher: keybindingMatcher,
            contextProvider: { [weak self] in
                self?.currentCommandContext() ?? .empty
            },
            themeProvider: { [weak self] in
                let background = self?.sessionStore.terminalBackgroundColor ?? .windowBackgroundColor
                return LeaderHintTheme(
                    background: Color(nsColor: background),
                    accent: Color(nsColor: self?.sessionStore.terminalAccentColor ?? .controlAccentColor),
                    isDark: background.isDark
                )
            },
            parentWindowProvider: { [weak self] in self?.window },
            // Redraw when a workspace fetch lands. Hopped to the next main
            // turn: `@Published` emits in willSet, and the redraw rereads
            // the store through `currentCommandContext()`.
            contentChanged: sessionStore.$workspaces
                .map { _ in () }
                .receive(on: DispatchQueue.main)
                .eraseToAnyPublisher()
        )
        overlay.start()
        leaderOverlay = overlay
        leaderBeginObserver = keybindingMatcher.$leaderPath
            .map { $0 != nil }
            .removeDuplicates()
            .filter { $0 }
            .sink { [weak self] _ in self?.refreshWorkspacesForLeader() }

        // Installed after `keybindingMatcher`'s own monitor: both watch
        // `.keyDown`, and this one must never fire for a key an app
        // shortcut already consumed.
        workspaceRefreshMonitor.install()

        // Finish wiring the attention notifier now that the app is up: give it
        // the user's preferences, a way to surface a session on click, and
        // (in the packaged app) notification authorization.
        sessionStore.notifier.settings = notificationSettings
        sessionStore.notifier.onActivateSession = { [weak self] id in
            self?.activateSession(id)
        }
        sessionStore.notifier.requestAuthorization()

        setUpStatusItem()

        // When the terminal theme changes, re-tint the AppKit chrome (the
        // SwiftUI sidebar re-reads the published colors on its own).
        terminalColorObserver = sessionStore.$terminalBackgroundColor
            .sink { [weak self] color in self?.applyTerminalChromeColor(color) }

        // Drive the sidebar width off the store's collapsed flag, which the
        // sidebar's own button and the View menu both toggle. `@Published`
        // replays its current value on subscribe, so a sidebar restored
        // collapsed applies the collapsed width on this first emission -- no
        // expanded-width flash before it snaps shut (see
        // `SidebarStateRestorationCombineTests`).
        sidebarObserver = sidebarSettings.$isCollapsed.sink { [weak self] collapsed in
            guard let self else { return }
            self.applySidebarWidth(collapsed: collapsed, style: self.sidebarSettings.collapseStyle)
        }

        // Re-apply the width when the collapse *style* changes (icons vs.
        // hidden), so flipping the preference while collapsed updates live.
        // Uses the emitted `style` directly, NOT `sidebarSettings.collapseStyle`
        // -- `@Published`'s publisher fires from `willSet`, so a synchronous
        // re-read here would still see the OLD value (see
        // `SidebarWidthPlanner`'s doc comment).
        sidebarStyleObserver = sidebarSettings.$collapseStyle.sink { [weak self] style in
            guard let self else { return }
            self.applySidebarWidth(collapsed: self.sidebarSettings.isCollapsed, style: style)
        }

        // Show/hide the right file sidebar on its preference. `@Published`
        // replays the current value on subscribe, so a launch with the sidebar
        // enabled applies it here (and one disabled leaves it hidden).
        fileSidebarObserver = fileSidebarPreferences.$isVisible.sink { [weak self] visible in
            self?.applyFileSidebarVisibility(visible)
        }

        presentLaunchOnboarding(onboarding, root: root)
    }

    /// Shows this launch's tour or What's New over the main window, and
    /// records it as seen once closed (quitting first shows it again).
    private func presentLaunchOnboarding(_ presentation: OnboardingPresentation, root: URL) {
        let acknowledge = { OnboardingLaunch.acknowledge(root: root, currentVersion: OnboardingLaunch.bundleVersion) }
        switch presentation {
        case .none: return
        case .tutorial: onboardingController.show(.tutorial(tutorialSteps(), setup: multiplexerSetup), onClose: acknowledge)
        case .whatsNew(let notes): onboardingController.show(.whatsNew(notes), onClose: acknowledge)
        }
    }

    /// The tour with the user's current shortcuts and leader sequences.
    private func tutorialSteps() -> [TutorialStep] {
        TutorialContent.steps(
            bindings: keybindingMatcher.bindings,
            leader: keybindingMatcher.leaderSettings,
            leaderSequences: paletteLeaderSequences()
        )
    }

    /// Shows or hides the right file sidebar pane, sizing it to the persisted
    /// width when shown and kicking off a working-directory resolve so it isn't
    /// blank on first reveal.
    private func applyFileSidebarVisibility(_ visible: Bool) {
        guard let splitView, let container = fileSidebarContainerView else { return }
        let isAttached = container.superview === splitView

        if visible, !isAttached {
            let width = CGFloat(fileSidebarPreferences.clampedWidth)
            container.frame.size.width = width
            splitView.addArrangedSubview(container)
            splitView.setHoldingPriority(.defaultHigh, forSubviewAt: splitView.arrangedSubviews.count - 1)
            splitView.layoutSubtreeIfNeeded()
            // Position after the layout pass has created the second divider,
            // so this actually sizes the file sidebar to `width`.
            DispatchQueue.main.async { [weak self] in
                guard let self, let splitView = self.splitView, splitView.arrangedSubviews.count >= 3 else { return }
                splitView.setPosition(splitView.bounds.width - width, ofDividerAt: 1)
                splitView.layoutSubtreeIfNeeded()
            }
            sessionStore.refreshFileSidebarRoot()
        } else if !visible, isAttached {
            container.removeFromSuperview()
            splitView.layoutSubtreeIfNeeded()
        }
        splitView.needsDisplay = true
        splitView.window?.viewsNeedDisplay = true
    }

    func applicationShouldTerminateAfterLastWindowClosed(_: NSApplication) -> Bool {
        true
    }

    func applicationDidResignActive(_: Notification) {
        // A leader sequence left pending while switching away would silently
        // swallow the first keys typed on return.
        guard stores != nil else { return }
        keybindingMatcher.cancelLeader()
    }

    func applicationDidBecomeActive(_: Notification) {
        // `stores` is nil until partway through `applicationDidFinishLaunching`
        // (it needs the display-session and Application Support guards to
        // pass first) -- showing either guard's modal fatal alert can itself
        // trigger this callback, before `stores` exists.
        guard stores != nil else { return }
        // Keep the "Attach existing" list fresh when returning to the app.
        sessionStore.refreshDiscovery()
        // A session already selected while the app was inactive when it went
        // to `.attention` needs this explicit clear -- `select(_:)` never
        // re-fires for an already-selected session (see
        // `SessionStore.clearUnreadForSelectedSessionIfAppActive`).
        sessionStore.clearUnreadForSelectedSessionIfAppActive()
        // Returning to the app is the moment a just-pushed PR or finished CI
        // run is most likely to matter; refetch the focused repository now.
        sessionStore.refreshPullRequestStatus(forceFocused: true)
    }

    /// Moves the divider between the full panel and the icon rail. Done without
    /// implicit animation: animating `setPosition` (especially with a nested
    /// `layoutSubtreeIfNeeded`) leaves a stale divider streak. We force a clean
    /// full redraw instead. `style` is always the caller's own current/emitted
    /// value (see `SidebarWidthPlanner`'s doc comment for why this can't just
    /// re-read `sidebarSettings.collapseStyle` from every call site).
    private func applySidebarWidth(collapsed: Bool, style: SidebarCollapseStyle) {
        guard let splitView else { return }
        let target = SidebarWidthPlanner.width(
            collapsed: collapsed,
            style: style,
            collapsedWidth: collapsedSidebarWidth,
            expandedWidth: resolvedExpandedWidth()
        )
        splitView.setPosition(target, ofDividerAt: 0)
        splitView.layoutSubtreeIfNeeded()
        splitView.needsDisplay = true
        splitView.window?.viewsNeedDisplay = true
    }

    /// A menu item that runs `command` through `perform(_:)`, the same path
    /// its chord, leader sequence and ⌘K row take. No key equivalent: menu
    /// items never carry one (docs/architecture.md's "Keybindings routed
    /// through the matcher, not menu key equivalents" invariant).
    private func commandMenuItem(_ title: String, _ command: AppCommand) -> NSMenuItem {
        let item = NSMenuItem(title: title, action: #selector(performMenuCommand(_:)), keyEquivalent: "")
        item.target = self
        item.representedObject = command
        return item
    }

    @objc private func performMenuCommand(_ sender: NSMenuItem) {
        guard let command = sender.representedObject as? AppCommand else { return }
        perform(command)
    }

    /// Re-applies the terminal theme's background to the AppKit sidebar/terminal
    /// chrome, and flips the sidebar's appearance to keep its text legible.
    private func applyTerminalChromeColor(_ color: NSColor) {
        sidebarContainerView?.layer?.backgroundColor = color.cgColor
        terminalWrapperView?.layer?.backgroundColor = color.cgColor
        sidebarHostView?.appearance = NSAppearance(named: color.isDark ? .darkAqua : .aqua)
        fileSidebarContainerView?.layer?.backgroundColor = color.cgColor
        fileSidebarHostView?.appearance = NSAppearance(named: color.isDark ? .darkAqua : .aqua)
    }

    private func makeWindow() -> NSWindow {
        let split = SeamlessSplitView()
        split.isVertical = true
        split.dividerStyle = .thin
        // Persist a user-dragged width as the new expanded width, but only when
        // it's a genuine resize: `SidebarWidthCapture` rejects drags taken while
        // collapsed (a programmatic collapse must never be saved as the expanded
        // width) and out-of-range/degenerate positions.
        split.onDividerDragEnded = { [weak self] width in
            guard let self else { return }
            // `mouseDown` also fires for a plain divider click (no resize), and
            // `@Published`'s `didSet` persists even an unchanged assignment, so
            // only write when the width actually changed.
            if let captured = SidebarWidthCapture.accepted(
                position: width,
                isCollapsed: self.sidebarSettings.isCollapsed,
                minimum: self.minimumExpandedSidebarWidth,
                maximum: self.maximumExpandedSidebarWidth
            ), captured != self.sidebarSettings.expandedWidth {
                self.sidebarSettings.expandedWidth = captured
            }
        }

        // The sidebar paints itself the terminal theme's background color, so
        // it and the opaque terminal read as one continuous surface (the hidden
        // divider completes the seam). A solid color -- not vibrancy -- because
        // the goal is to *match* the terminal, which a translucent material
        // can't do. The hosting view's appearance is forced to match the
        // background's darkness so SwiftUI text/selection stay legible whatever
        // the app's chrome appearance is set to.
        let sidebarHost = NSHostingView(
            rootView: SidebarView()
                .environmentStores(stores)
        )
        sidebarHost.appearance = NSAppearance(
            named: sessionStore.terminalBackgroundColor.isDark ? .darkAqua : .aqua
        )
        sidebarHostView = sidebarHost

        let sidebarContainer = NSView()
        sidebarContainer.wantsLayer = true
        sidebarContainer.layer?.backgroundColor = sessionStore.terminalBackgroundColor.cgColor
        // Start at the persisted expanded width so a restored-expanded sidebar
        // doesn't flash the default width first; a restored-collapsed sidebar
        // is snapped shut by `$isCollapsed`'s replay-on-subscribe emission set
        // up in `applicationDidFinishLaunching`.
        sidebarContainer.frame = NSRect(x: 0, y: 0, width: resolvedExpandedWidth(), height: 640)
        sidebarContainerView = sidebarContainer
        // Frame + autoresizing, NOT Auto Layout: the split view drives the
        // container's frame imperatively (`setPosition` on collapse), and the
        // host autoresizes to fill it. Pinning the host with constraints fought
        // that frame-based sizing and hung the collapse layout pass.
        sidebarHost.frame = sidebarContainer.bounds
        sidebarHost.autoresizingMask = [.width, .height]
        sidebarContainer.addSubview(sidebarHost)

        // Reserve the titlebar band on the terminal side too. With
        // `fullSizeContentView` the content spans under the titlebar, so the
        // terminal is inset down by the titlebar height and backed with the
        // same dark color. That keeps the traffic lights over an empty dark
        // band in every sidebar state -- expanded, icon rail, or hidden --
        // instead of on top of live terminal content. The host container stays
        // a permanent AppKit subview (docs/architecture.md, "Permanent AppKit
        // terminal host"); wrapping it in a plain inset view doesn't touch
        // any surface.
        let terminalContainer = sessionStore.hostContainer
        let terminalWrapper = NSView()
        terminalWrapper.wantsLayer = true
        terminalWrapper.layer?.backgroundColor = sessionStore.terminalBackgroundColor.cgColor
        terminalWrapper.frame = NSRect(x: 0, y: 0, width: 860, height: 640)
        terminalWrapperView = terminalWrapper
        // A small left gap (filled by the wrapper's dark background) gives the
        // terminal content breathing room from the sidebar -- a bit of a spacer.
        let terminalGap: CGFloat = 8
        terminalContainer.frame = NSRect(
            x: terminalGap, y: 0,
            width: 860 - terminalGap, height: 640 - titlebarInset
        )
        // Flexible width/height; fixed left gap, top band, and bottom.
        terminalContainer.autoresizingMask = [.width, .height]
        terminalWrapper.addSubview(terminalContainer)

        // The right-hand file sidebar: a third pane hosting `FileSidebarView`.
        // Painted the terminal background like the left sidebar so the three
        // panes read as one surface. Starts hidden unless the preference is on
        // (the `$isVisible` subscription re-applies this on launch too).
        let fileSidebarHost = NSHostingView(rootView: FileSidebarView().environmentStores(stores))
        fileSidebarHost.appearance = NSAppearance(named: sessionStore.terminalBackgroundColor.isDark ? .darkAqua : .aqua)
        fileSidebarHostView = fileSidebarHost

        let fileSidebarContainer = NSView()
        fileSidebarContainer.wantsLayer = true
        fileSidebarContainer.layer?.backgroundColor = sessionStore.terminalBackgroundColor.cgColor
        fileSidebarContainer.frame = NSRect(x: 0, y: 0, width: CGFloat(fileSidebarPreferences.clampedWidth), height: 640)
        fileSidebarHost.frame = fileSidebarContainer.bounds
        fileSidebarHost.autoresizingMask = [.width, .height]
        fileSidebarContainer.addSubview(fileSidebarHost)
        fileSidebarContainerView = fileSidebarContainer
        // The file sidebar is added to / removed from the split on demand by
        // `applyFileSidebarVisibility` (add/remove is far more predictable than
        // hiding an arranged subview), so it is NOT added here.

        split.addArrangedSubview(sidebarContainer)
        split.addArrangedSubview(terminalWrapper)
        // Sidebar keeps its width when the window resizes; the terminal flexes.
        split.setHoldingPriority(.defaultHigh, forSubviewAt: 0)
        // Persist a user-dragged file-sidebar width (the second divider); only
        // when it's attached and actually changed.
        split.onFileSidebarDragEnded = { [weak self] width in
            guard let self, self.fileSidebarContainerView?.superview != nil else { return }
            let clamped = FileSidebarPreferences(width: Double(width)).clampedWidth
            if abs(clamped - self.fileSidebarPreferences.width) > 0.5 {
                self.fileSidebarPreferences.width = clamped
            }
        }
        self.splitView = split

        let window = NSWindow(
            contentRect: NSRect(x: 0, y: 0, width: 1080, height: 640),
            styleMask: [.titled, .closable, .miniaturizable, .resizable, .fullSizeContentView],
            backing: .buffered,
            defer: false
        )
        window.title = "Vakta"
        // Full-height sidebar: the content view (the split view) spans the whole
        // window, including behind the titlebar, so the sidebar's vibrancy runs
        // all the way to the top with the traffic lights floating over it --
        // like Mail/Finder. The sidebar insets its own header below the traffic
        // lights (see `SidebarView`). No opaque titlebar strip, no title text.
        window.titlebarAppearsTransparent = true
        window.titleVisibility = .hidden
        window.contentView = split
        window.center()
        // `AppDelegate` (this object) holds `window` with a strong Swift
        // reference; AppKit's default `isReleasedWhenClosed = true` would
        // additionally release it when the user closes it, over-releasing
        // and crashing on next access (e.g. on quit).
        window.isReleasedWhenClosed = false
        return window
    }

    /// Settled design decision #5: the menu bar is deliberately free of
    /// every `keyEquivalent`. Any `⌘`-based key equivalent set here would
    /// let AppKit's menu system swallow the keystroke before it ever reaches
    /// the responder chain -- before even `KeybindingMatcher`'s local
    /// monitor gets a look, per Apple's documented event dispatch order.
    /// herdr (and Vakta's own chord) must see every key; menu items here are
    /// mouse/trackpad-only by design.
    private func buildMainMenu() {
        let mainMenu = NSMenu()

        let appMenuItem = NSMenuItem()
        let appMenu = NSMenu()
        appMenu.addItem(withTitle: "About Vakta", action: nil, keyEquivalent: "")
        appMenu.addItem(.separator())
        // No ⌘ key equivalent: docs/architecture.md's "Keybindings routed through
        // the matcher, not menu key equivalents" invariant keeps every menu
        // item keyless so keystrokes reach herdr. Preferences is reachable by
        // mouse here, and the user can bind it (and Toggle Sidebar) to a chord
        // inside the pane -- that goes through `KeybindingMatcher`, which by
        // design sees keys before the menu ever could.
        appMenu.addItem(commandMenuItem("Preferences…", .openPreferences))
        appMenu.addItem(.separator())
        // Standard selectors sent to `nil`/`NSApp` -- AppKit resolves and
        // enables/disables these itself, same as every other Mac app. No
        // keyEquivalent, per this method's doc comment; ⌘H/⌥⌘H aren't routed
        // through `KeybindingMatcher` (mouse/trackpad-only for now).
        let hideItem = NSMenuItem(title: "Hide Vakta", action: #selector(NSApplication.hide(_:)), keyEquivalent: "")
        appMenu.addItem(hideItem)
        let hideOthersItem = NSMenuItem(
            title: "Hide Others",
            action: #selector(NSApplication.hideOtherApplications(_:)),
            keyEquivalent: ""
        )
        appMenu.addItem(hideOthersItem)
        let showAllItem = NSMenuItem(
            title: "Show All",
            action: #selector(NSApplication.unhideAllApplications(_:)),
            keyEquivalent: ""
        )
        appMenu.addItem(showAllItem)
        appMenu.addItem(.separator())
        let quitItem = NSMenuItem(
            title: "Quit Vakta",
            action: #selector(NSApplication.terminate(_:)),
            keyEquivalent: ""
        )
        quitItem.target = NSApp
        appMenu.addItem(quitItem)
        appMenuItem.submenu = appMenu
        mainMenu.addItem(appMenuItem)

        let editMenuItem = NSMenuItem()
        let editMenu = NSMenu(title: "Edit")
        // Standard Cut/Copy/Paste, `target = nil` so AppKit routes each down
        // the real first-responder chain (auto-enabling/disabling to match)
        // -- the same dispatch `KeybindingMatcher`'s ⌘X/⌘C/⌘V onMatch handler
        // uses. No keyEquivalent, per this method's doc comment: the chords
        // are handled by the matcher before the menu could ever see them.
        let cutItem = NSMenuItem(title: "Cut", action: #selector(NSText.cut(_:)), keyEquivalent: "")
        editMenu.addItem(cutItem)
        let copyItem = NSMenuItem(title: "Copy", action: #selector(NSText.copy(_:)), keyEquivalent: "")
        editMenu.addItem(copyItem)
        let pasteItem = NSMenuItem(title: "Paste", action: #selector(NSText.paste(_:)), keyEquivalent: "")
        editMenu.addItem(pasteItem)
        editMenu.addItem(.separator())
        let selectAllItem = NSMenuItem(title: "Select All", action: #selector(NSText.selectAll(_:)), keyEquivalent: "")
        editMenu.addItem(selectAllItem)
        editMenuItem.submenu = editMenu
        mainMenu.addItem(editMenuItem)

        let sessionMenuItem = NSMenuItem()
        let sessionMenu = NSMenu(title: "Session")

        // "New Session" is a submenu of profiles; its first item (the default
        // profile) doubles as the plain "new session" action. Rebuilt from
        // current `sessionStore.profiles` every time it's about to open
        // (`menuNeedsUpdate(_:)` below) rather than once here at launch --
        // editing/deleting a profile must be reflected immediately, and a
        // stale item must not be able to launch a deleted profile or an
        // obsolete command snapshot (hence `representedObject` holding only
        // the profile's stable id, resolved back to a live `Profile` at
        // click time in `newSessionFromProfile`).
        let newSessionItem = NSMenuItem(title: "New Session", action: nil, keyEquivalent: "")
        let profilesMenu = NSMenu(title: "New Session")
        profilesMenu.delegate = self
        newSessionProfilesMenu = profilesMenu
        newSessionItem.submenu = profilesMenu
        sessionMenu.addItem(newSessionItem)

        // Session switcher (⌘K by default, bound via KeybindingMatcher). No
        // keyEquivalent here -- see docs/architecture.md's "Keybindings routed
        // through the matcher, not menu key equivalents" invariant; the chord
        // is handled earlier.
        sessionMenu.addItem(.separator())
        sessionMenu.addItem(commandMenuItem("Switch Session…", .openSessionSwitcher))

        // No keyEquivalent, per this method's doc comment; a rebindable
        // shortcut would go through `KeybindingMatcher`, not here.
        sessionMenu.addItem(.separator())
        sessionMenu.addItem(commandMenuItem("Open in Editor", .openInEditor))

        sessionMenuItem.submenu = sessionMenu
        mainMenu.addItem(sessionMenuItem)

        let viewMenuItem = NSMenuItem()
        let viewMenu = NSMenu(title: "View")
        // No key equivalent, to keep every keystroke flowing to the terminal
        // (docs/architecture.md's "Keybindings routed through the matcher, not menu
        // key equivalents" invariant). The sidebar's own button and the
        // Ctrl+Shift+num chords are the keyboard-free / rebindable paths.
        viewMenu.addItem(commandMenuItem("Toggle Sidebar", .toggleSidebar))
        viewMenu.addItem(.separator())
        viewMenu.addItem(commandMenuItem("Increase Font Size", .increaseFontSize))
        viewMenu.addItem(commandMenuItem("Decrease Font Size", .decreaseFontSize))
        viewMenu.addItem(commandMenuItem("Reset Font Size", .resetFontSize))
        viewMenuItem.submenu = viewMenu
        mainMenu.addItem(viewMenuItem)

        // Assigning `NSApp.helpMenu` is what makes AppKit add its built-in
        // "search menu items" field (⇧⌘/) above these items.
        let helpMenuItem = NSMenuItem()
        let helpMenu = NSMenu(title: "Help")
        helpMenu.addItem(commandMenuItem("Welcome Tour", .showWelcomeTour))
        helpMenu.addItem(commandMenuItem("What's New in Vakta", .showWhatsNew))
        helpMenuItem.submenu = helpMenu
        mainMenu.addItem(helpMenuItem)
        NSApp.helpMenu = helpMenu

        NSApp.mainMenu = mainMenu
    }

    private func presentFatalAlert(_ title: String, _ message: String) {
        let alert = NSAlert()
        alert.messageText = title
        alert.informativeText = message
        alert.alertStyle = .critical
        alert.runModal()
    }

    /// Non-fatal user-facing errors (e.g. "Open in Editor" failure
    /// outcomes) -- same mechanism as `presentFatalAlert`, a `.warning`
    /// style instead of `.critical`.
    private func presentAlert(_ title: String, _ message: String) {
        let alert = NSAlert()
        alert.messageText = title
        alert.informativeText = message
        alert.alertStyle = .warning
        alert.runModal()
    }

    @objc private func newSessionFromProfile(_ sender: NSMenuItem) {
        // Resolved by id against CURRENT profiles, never a value captured
        // when the menu was built -- the profile may have been edited (a
        // stale snapshot would launch the old command) or deleted (a stale
        // id must fall back to the default rather than launching nothing or
        // crashing) since the menu last opened.
        guard let id = sender.representedObject as? Profile.ID,
              let profile = sessionStore.profiles.first(where: { $0.id == id })
        else {
            sessionStore.createSession()
            return
        }
        sessionStore.createSession(profile: profile)
    }

    // MARK: Menu-bar status item

    /// Creates the menu-bar extra and keeps its icon in sync with agent status.
    /// The dropdown itself is (re)built lazily in `menuNeedsUpdate(_:)`.
    private func setUpStatusItem() {
        let item = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
        item.button?.imagePosition = .imageLeading
        let menu = NSMenu()
        menu.delegate = self
        item.menu = menu
        statusItem = item
        updateStatusItemButton(sessionStore.agentStatus)

        // `@Published` fires before the stored value updates, so read the
        // emitted value rather than `sessionStore.agentStatus`.
        agentStatusObserver = sessionStore.$agentStatus.sink { [weak self] status in
            self?.updateStatusItemButton(status)
        }
        // Reflect passthrough mode in the menu-bar item too.
        passthroughObserver = keybindingMatcher.$passthrough.sink { [weak self] _ in
            guard let self else { return }
            self.updateStatusItemButton(self.sessionStore.agentStatus)
        }
    }

    /// Icon reflects the busiest state across sessions; a count trails it when
    /// any session is waiting on the user.
    private func updateStatusItemButton(_ status: [Session.ID: AgentStatus]) {
        guard let button = statusItem?.button else { return }

        // Passthrough mode takes over the indicator while it's active.
        if keybindingMatcher.passthrough {
            let image = NSImage(systemSymbolName: "keyboard.fill", accessibilityDescription: "Passthrough mode on")
            image?.isTemplate = true
            button.image = image
            button.title = " raw"
            button.toolTip = "Passthrough on — keys go straight to the session. Double-tap the modifier to exit."
            return
        }
        button.toolTip = nil

        let waiting = status.values.filter { $0 == .attention }.count
        let working = status.values.filter { $0 == .working }.count

        // Symbols chosen from the macOS 11 set so they resolve on the 13.0
        // deployment target (a missing symbol renders no icon at all).
        let symbol: String
        if waiting > 0 {
            symbol = "exclamationmark.circle.fill"
        } else if working > 0 {
            symbol = "ellipsis.circle"
        } else {
            symbol = "terminal"
        }
        let image = NSImage(systemSymbolName: symbol, accessibilityDescription: "Vakta agent status")
        image?.isTemplate = true
        button.image = image
        button.title = waiting > 0 ? " \(waiting)" : ""
    }

    /// A small filled dot in the session's status color, for menu-bar rows
    /// (non-template so the color shows, unlike the monochrome button icon).
    /// `.done` renders as a green checkmark instead of a plain dot -- a real
    /// completion (herdr's own "done"/"complete") reads differently from
    /// merely being idle.
    private func statusDotImage(_ status: AgentStatus) -> NSImage {
        if status == .done {
            let config = NSImage.SymbolConfiguration(paletteColors: [.systemGreen])
            return NSImage(systemSymbolName: "checkmark.circle.fill", accessibilityDescription: "Done")?
                .withSymbolConfiguration(config) ?? NSImage()
        }

        let color: NSColor
        switch status {
        case .working: color = .systemOrange
        case .attention: color = .systemYellow
        case .idle: color = .systemGreen
        case .done: color = .systemGreen // unreachable -- handled above; kept for exhaustiveness
        case .none, .unavailable: color = .tertiaryLabelColor
        }
        let size = NSSize(width: 10, height: 10)
        let image = NSImage(size: size)
        image.lockFocus()
        color.setFill()
        NSBezierPath(ovalIn: NSRect(origin: .zero, size: size)).fill()
        image.unlockFocus()
        image.isTemplate = false
        return image
    }

    @objc private func menuBarSelectSession(_ sender: NSMenuItem) {
        guard let id = sender.representedObject as? UUID else { return }
        activateSession(id)
    }

    @objc private func showMainWindow() {
        window?.makeKeyAndOrderFront(nil)
        NSApp.activate(ignoringOtherApps: true)
    }

    /// Selects a session and brings Vakta to the front -- shared by the
    /// menu-bar rows and notification taps.
    private func activateSession(_ id: Session.ID) {
        sessionStore.select(id)
        window?.makeKeyAndOrderFront(nil)
        NSApp.activate(ignoringOtherApps: true)
    }

    // MARK: Session switcher (⌘K)

    /// Mirrors `SidebarView.supportsWorkspaces` -- whether querying
    /// `session`'s workspaces makes sense at all.
    private static func supportsWorkspaces(_ session: Session) -> Bool {
        LaunchTargetResolver.supportsWorkspaces(session.profile, sessionName: session.sessionName)
    }

    /// The live snapshot `CommandAvailability` decides against: whether the
    /// selected session's backend can perform the mutating multiplexer
    /// commands, and which sessions `selectSession(i)` can reach.
    private func currentCommandContext() -> CommandContext {
        let sessionTitles = sessionStore.sessions.map(\.displayTitle)
        guard let id = sessionStore.selectedID,
              let session = sessionStore.sessions.first(where: { $0.id == id })
        else { return CommandContext(supportsSelectedSessionActions: false, sessionTitles: sessionTitles) }
        let workspaces = Self.supportsWorkspaces(session) ? sessionStore.workspaces[id] ?? [] : []
        return CommandContext(
            supportsSelectedSessionActions: LaunchTargetResolver.supportsActions(session.profile, sessionName: session.sessionName),
            sessionTitles: sessionTitles,
            workspaceTitles: workspaces.map(\.label),
            focusedWorkspaceIndex: workspaces.firstIndex(where: \.focused)
        )
    }

    /// Each command's leader sequence for the ⌘K rows, or none while leader
    /// keys are off (a sequence you can't type would only mislead).
    private func paletteLeaderSequences() -> [AppCommand: String] {
        guard keybindingMatcher.leaderSettings.isEnabled else { return [:] }
        return keybindingMatcher.leaderRoot.commandPaths().mapValues(LeaderHintAssembler.sequence(for:))
    }

    /// Starting a leader sequence refreshes the selected session's workspace
    /// cache, so `TAB` lists current names (the cache otherwise only fills
    /// on sidebar disclosure or ⌘K).
    private func refreshWorkspacesForLeader() {
        guard let id = sessionStore.selectedID,
              let session = sessionStore.sessions.first(where: { $0.id == id }),
              Self.supportsWorkspaces(session)
        else { return }
        sessionStore.fetchWorkspaces(for: id)
    }

    /// Opens (or refocuses) the command palette: sessions, workspaces, and
    /// static actions in one flat, searchable list.
    private func showSessionSwitcher() {
        switcherModel.onQueryChanged = nil
        globalPaneFetchGeneration = nil
        let sessions = sessionStore.sessions.map {
            PaletteItemAssembler.SessionEntry(id: $0.id, title: $0.displayTitle, status: sessionStore.agentStatus[$0.id] ?? .none)
        }
        // Hide commands the selected session can't act on -- the ⌘K
        // equivalent of the sidebar menu living only on workspace rows.
        let context = currentCommandContext()
        let commands = AppCommandCatalog.paletteCommands.filter {
            CommandAvailability.isAvailable($0, in: context)
        }
        let items = PaletteItemAssembler.assemble(
            sessions: sessions,
            workspaces: [:],
            workspaceStatus: sessionStore.paneStatusByWorkspaceID,
            commands: commands,
            leaderSequences: paletteLeaderSequences()
        )
        let generation = switcherModel.reset(items: items)
        switcherModel.onNavigation = nil
        switcherModel.onSelect = { [weak self] item in self?.selectFromSwitcher(item) }
        switcherModel.onCancel = { [weak self] in self?.closeSwitcher() }
        switcherModel.onScopeRequested = { [weak self] scope in
            self?.requestSessionSwitcherScope(scope, generation: generation)
        }
        switcherModel.onQueryChanged = { [weak self] query in
            self?.requestGlobalPaneSearch(query, generation: generation)
        }
        workspacesObserver = nil
        panesObserver = nil
        requestRootWorkspaceRows(generation: generation)

        if let panel = switcherPanel {
            // Refresh theme colors on every reopen (cheap, and covers a
            // theme change made while the palette was closed) -- the panel
            // itself is reused rather than recreated.
            applySwitcherTheme(to: panel)
            panel.center()
            panel.makeKeyAndOrderFront(nil)
            NSApp.activate(ignoringOtherApps: true)
            return
        }

        let host = NSHostingView(rootView: SessionSwitcherView(model: switcherModel))
        switcherHostView = host
        let panel = SessionSwitcherPanel(
            contentRect: NSRect(x: 0, y: 0, width: 440, height: 360),
            styleMask: [.titled, .fullSizeContentView],
            backing: .buffered,
            defer: false
        )
        panel.model = switcherModel
        panel.titleVisibility = .hidden
        panel.titlebarAppearsTransparent = true
        panel.isMovableByWindowBackground = true
        panel.isFloatingPanel = true
        panel.level = .floating
        // Dismissal is handled by `windowDidResignKey` (covers ⌘-Tab away and
        // clicking elsewhere). We deliberately do NOT also set
        // `hidesOnDeactivate`, which can re-order the panel back in on
        // reactivation and fight the delegate.
        panel.animationBehavior = .utilityWindow
        panel.contentView = host
        panel.delegate = self
        // Held strongly here; stop AppKit additionally releasing on close.
        panel.isReleasedWhenClosed = false
        switcherPanel = panel
        applySwitcherTheme(to: panel)

        panel.center()
        panel.makeKeyAndOrderFront(nil)
        NSApp.activate(ignoringOtherApps: true)
    }

    private func requestRootWorkspaceRows(generation: Int) {
        let sessionIDs = PaletteRootWorkspacePlanner.fetchSessionIDs(
            sessionStore.sessions.map {
                PaletteWorkspaceSession(id: $0.id, supportsWorkspaces: Self.supportsWorkspaces($0))
            }
        )
        pendingPaletteWorkspaceFetches = Set(sessionIDs)
        guard !pendingPaletteWorkspaceFetches.isEmpty else { return }

        workspacesObserver = sessionStore.$workspaces.sink { [weak self] workspacesByID in
            guard let self,
                  self.switcherModel.generation == generation,
                  self.switcherModel.scope == .root
            else { return }

            let pendingSessionIDs = self.pendingPaletteWorkspaceFetches
            for sessionID in pendingSessionIDs {
                guard let workspaces = workspacesByID[sessionID] else { continue }
                self.switcherModel.replaceWorkspaces(
                    self.paletteWorkspaceItems(for: sessionID, workspaces: workspaces),
                    forSessionID: sessionID,
                    forGeneration: generation
                )
                self.pendingPaletteWorkspaceFetches.remove(sessionID)
            }
            if self.pendingPaletteWorkspaceFetches.isEmpty {
                self.workspacesObserver = nil
            }
        }

        for sessionID in sessionIDs {
            sessionStore.fetchWorkspaces(for: sessionID)
        }
    }

    private func requestGlobalPaneSearch(_ rawQuery: String, generation: Int) {
        guard switcherModel.generation == generation,
              switcherModel.scope == .root,
              PaletteQuery.parse(rawQuery).mode == .allPanes,
              globalPaneFetchGeneration != generation
        else { return }

        globalPaneFetchGeneration = generation
        sessionStore.fetchGlobalPanes { [weak self] entries in
            guard let self, self.switcherModel.generation == generation else { return }
            self.switcherModel.replaceGlobalPaneItems(
                PaletteItemAssembler.assembleGlobalPanes(entries),
                forGeneration: generation
            )
        }
    }

    private func requestSessionSwitcherScope(_ scope: PaletteNavigationScope, generation: Int) {
        guard switcherModel.generation == generation else { return }

        switch scope {
        case .root:
            return
        case .workspaces(let sessionID):
            guard let session = sessionStore.sessions.first(where: { $0.id == sessionID }),
                  Self.supportsWorkspaces(session)
            else { return }

            let initialItems = paletteWorkspaceItems(for: sessionID, workspaces: sessionStore.workspaces[sessionID] ?? [])
            switcherModel.showScope(scope, items: initialItems)
            workspacesObserver = sessionStore.$workspaces.sink { [weak self] workspacesByID in
                guard let self,
                      self.switcherModel.generation == generation,
                      self.switcherModel.scope == scope,
                      let workspaces = workspacesByID[sessionID]
                else { return }
                self.switcherModel.replaceScopeItems(
                    self.paletteWorkspaceItems(for: sessionID, workspaces: workspaces),
                    for: scope
                )
                self.workspacesObserver = nil
            }
            sessionStore.fetchWorkspaces(for: sessionID)

        case .panes(let sessionID, let workspaceID):
            guard sessionStore.sessions.contains(where: { $0.id == sessionID }) else { return }
            let initialItems = PaletteItemAssembler.assemble(
                panes: sessionStore.panes[sessionID]?[workspaceID] ?? [],
                sessionID: sessionID,
                workspaceID: workspaceID
            )
            switcherModel.showScope(scope, items: initialItems)
            panesObserver = sessionStore.$panes.sink { [weak self] panesByID in
                guard let self,
                      self.switcherModel.generation == generation,
                      self.switcherModel.scope == scope,
                      let panes = panesByID[sessionID]?[workspaceID]
                else { return }
                self.switcherModel.replaceScopeItems(
                    PaletteItemAssembler.assemble(
                        panes: panes,
                        sessionID: sessionID,
                        workspaceID: workspaceID
                    ),
                    for: scope
                )
                self.panesObserver = nil
            }
            sessionStore.fetchPanes(for: sessionID, workspaceID: workspaceID)
        }
    }

    private func paletteWorkspaceItems(for sessionID: Session.ID, workspaces: [Workspace]) -> [PaletteItem] {
        guard let session = sessionStore.sessions.first(where: { $0.id == sessionID }) else { return [] }
        let entry = PaletteItemAssembler.SessionEntry(
            id: session.id,
            title: session.displayTitle,
            status: sessionStore.agentStatus[session.id] ?? .none
        )
        return PaletteItemAssembler.assemble(
            sessions: [entry],
            workspaces: [sessionID: workspaces],
            workspaceStatus: sessionStore.paneStatusByWorkspaceID,
            commands: []
        ).filter { $0.category == .workspace }
    }

    /// Repaints the palette in the current terminal theme's colors -- same
    /// solid-background choice `makeWindow` uses for the sidebar/terminal
    /// seam -- and flips the panel's appearance to match, so standard
    /// controls (the search field's cursor/selection) stay legible against
    /// a background that may be darker or lighter than the system chrome.
    private func applySwitcherTheme(to panel: SessionSwitcherPanel) {
        let background = sessionStore.terminalBackgroundColor
        switcherHostView?.rootView = SessionSwitcherView(
            model: switcherModel,
            highlightColor: Color(nsColor: sessionStore.terminalSelectionColor),
            backgroundColor: Color(nsColor: background),
            accentColor: Color(nsColor: sessionStore.terminalAccentColor)
        )
        panel.appearance = NSAppearance(named: background.isDark ? .darkAqua : .aqua)
    }

    private func selectFromSwitcher(_ item: PaletteItem) {
        switcherPanel?.orderOut(nil)
        switch item.kind {
        case .selectSession(let id):
            activateSession(id)
        case .focusWorkspace(let sessionID, let workspaceID):
            sessionStore.focusWorkspace(workspaceID, in: sessionID)
            activateSession(sessionID)
        case .focusPane(let sessionID, let workspaceID, let paneID):
            sessionStore.focusPane(paneID, workspaceID: workspaceID, in: sessionID)
            activateSession(sessionID)
        case .command(let command):
            perform(command)
        }
    }

    /// The one dispatcher for every `AppCommand`, whether it came from a
    /// chord (`keybindingMatcher`) or a palette row. A command the current
    /// context can't act on is a silent no-op: palette rows can outlive a
    /// selection change, and a bound chord is consumed regardless so its
    /// meaning never depends on which session is selected.
    private func perform(_ command: AppCommand) {
        guard CommandAvailability.isAvailable(command, in: currentCommandContext()) else { return }
        switch command {
        case .selectSession(let index): sessionStore.selectSession(at: index)
        case .toggleSidebar: sidebarSettings.toggleCollapsed()
        case .openPreferences: preferencesController.show()
        case .openSessionSwitcher: showSessionSwitcher()
        case .quit: NSApp.terminate(nil)
        // Dispatched down the real first-responder chain rather than
        // called directly: `AppTerminalView` (GhosttyTerminal) already
        // overrides `copy(_:)`/`paste(_:)` as NSResponder actions, and a
        // focused text field's own field editor implements all three
        // natively -- one dispatch serves both without a seam.
        case .copy: NSApp.sendAction(#selector(NSText.copy(_:)), to: nil, from: nil)
        case .paste: NSApp.sendAction(#selector(NSText.paste(_:)), to: nil, from: nil)
        case .cut: NSApp.sendAction(#selector(NSText.cut(_:)), to: nil, from: nil)
        case .selectAll: NSApp.sendAction(#selector(NSText.selectAll(_:)), to: nil, from: nil)
        // Closes whichever window is actually key (main window or
        // Preferences), same as clicking its red button.
        case .closeWindow: NSApp.sendAction(#selector(NSWindow.performClose(_:)), to: nil, from: nil)
        case .increaseFontSize: sessionStore.performBindingActionOnSelectedSession("increase_font_size:1")
        case .decreaseFontSize: sessionStore.performBindingActionOnSelectedSession("decrease_font_size:1")
        case .resetFontSize: sessionStore.performBindingActionOnSelectedSession("reset_font_size")
        case .nextUnreadSession: sessionStore.goToNextUnreadSession()
        case .newSession: sessionStore.createSession()
        case .toggleFileSidebar: fileSidebarPreferences.isVisible.toggle()
        case .toggleFileSidebarChanges:
            fileSidebarPreferences.apply(FileSidebarModePlanner.togglingChanges(fileSidebarPreferences.preferences))
        case .openInEditor: openInEditor()
        case .splitPaneRight: performWorkspacePaneAction { .splitPane(paneID: $0, direction: .right) }
        case .splitPaneDown: performWorkspacePaneAction { .splitPane(paneID: $0, direction: .down) }
        case .zoomPane: performWorkspacePaneAction { .zoomPane(paneID: $0) }
        case .closePane: performWorkspacePaneAction { .closePane(paneID: $0) }
        case .renamePane: renameFocusedPane()
        case .closeWorkspace: performFocusedWorkspaceAction { .closeWorkspace(workspaceID: $0) }
        case .newWorkspace:
            if let id = sessionStore.selectedID { sessionStore.performAction(.createWorkspace(label: nil), in: id) }
        case .stopSession: confirmStopSelectedSession()
        case .editHerdrConfig: preferencesController.show(section: .herdr)
        case .reloadHerdrConfig: reloadHerdrConfig()
        case .showWelcomeTour: onboardingController.show(.tutorial(tutorialSteps(), setup: multiplexerSetup))
        case .showWhatsNew:
            onboardingController.show(.whatsNew(OnboardingPlanner.releaseHistory(
                currentVersion: OnboardingLaunch.bundleVersion, releaseNotes: WhatsNewCatalog.releaseNotes)))
        case .focusWorkspace(let index):
            // Resolved against the same cached list the availability check
            // (and the which-key row) used.
            guard let id = sessionStore.selectedID,
                  let workspaces = sessionStore.workspaces[id],
                  workspaces.indices.contains(index)
            else { return }
            sessionStore.focusWorkspace(workspaces[index].id, in: id)
        }
    }

    /// ⌘K workspace-level action on the selected session's focused workspace
    /// (the "act on the current selection" model). No selection or no focused
    /// workspace (e.g. a plain shell, or before the disclosure was ever
    /// opened): silent no-op, like Open in Editor with nothing to open.
    private func performFocusedWorkspaceAction(_ make: (String) -> MultiplexerAction) {
        guard let id = sessionStore.selectedID,
              let workspaceID = sessionStore.focusedWorkspaceID(in: id)
        else { return }
        sessionStore.performAction(make(workspaceID), in: id)
    }

    /// ⌘K pane-level action on the active pane of the selected session's
    /// focused workspace. The store resolves the exact pane cross-backend.
    private func performWorkspacePaneAction(_ make: @escaping (String) -> MultiplexerAction) {
        guard let id = sessionStore.selectedID,
              let workspaceID = sessionStore.focusedWorkspaceID(in: id)
        else { return }
        sessionStore.performPaneAction(make, workspaceID: workspaceID, in: id)
    }

    /// ⌘K "Stop Session": confirms, then ends the selected session on the
    /// server (`.stopSession`) -- not re-attachable, unlike Detach.
    private func confirmStopSelectedSession() {
        guard let id = sessionStore.selectedID,
              let session = sessionStore.sessions.first(where: { $0.id == id })
        else { return }
        let alert = NSAlert()
        alert.messageText = "Stop “\(session.displayTitle)”?"
        alert.informativeText = "This ends the session on the server. Detach instead if you want to keep it running in the background."
        alert.addButton(withTitle: "Stop")
        alert.addButton(withTitle: "Cancel")
        if alert.runModal() == .alertFirstButtonReturn {
            sessionStore.performAction(.stopSession, in: id)
        }
    }

    /// ⌘K "Rename Pane…": prompts for a name, then renames the active pane of
    /// the selected session's focused workspace. The name is gathered up front
    /// (a synchronous prompt) before the store resolves the pane off-main.
    private func renameFocusedPane() {
        guard let id = sessionStore.selectedID,
              let workspaceID = sessionStore.focusedWorkspaceID(in: id),
              let name = promptForText(title: "Rename Pane", message: "New name for the focused pane:"),
              !name.isEmpty
        else { return }
        sessionStore.performPaneAction({ .renamePane(paneID: $0, label: name) }, workspaceID: workspaceID, in: id)
    }

    /// A minimal single-line text prompt (an `NSAlert` with an accessory
    /// field). Returns the entered string, or `nil` if cancelled. AppKit lives
    /// here in the adapter, not in the store.
    private func promptForText(title: String, message: String) -> String? {
        let alert = NSAlert()
        alert.messageText = title
        alert.informativeText = message
        alert.addButton(withTitle: "Rename")
        alert.addButton(withTitle: "Cancel")
        let field = NSTextField(frame: NSRect(x: 0, y: 0, width: 240, height: 24))
        alert.accessoryView = field
        alert.window.initialFirstResponder = field
        return alert.runModal() == .alertFirstButtonReturn
            ? field.stringValue.trimmingCharacters(in: .whitespacesAndNewlines)
            : nil
    }

    /// ⌘K "Reload Herdr Config": asks the running herdr server to re-read its
    /// config. Silent on success; a failure is worth an alert since nothing
    /// else on screen would say the reload didn't happen.
    private func reloadHerdrConfig() {
        Task { @MainActor in
            guard case .failed(let reason) = await stores.herdrConfig.reloadServer() else { return }
            let alert = NSAlert()
            alert.messageText = "herdr did not reload its config"
            alert.informativeText = reason
            alert.runModal()
        }
    }

    // MARK: Open in Editor

    /// Resolves the selected session's focused-pane working directory
    /// (herdr/tmux active-pane query, falling back through OSC-7/profile
    /// launch directory) and launches it in the preferred editor. Every
    /// failure outcome surfaces to the user rather than a silent no-op.
    private func openInEditor() {
        guard let id = sessionStore.selectedID else { return }
        let installed = EditorLaunchAdapter.installedEditors()
        sessionStore.resolveOpenInEditor(
            for: id,
            editorChoice: editorPreferences.choice,
            installedEditors: installed
        ) { [weak self] outcome in
            self?.handleOpenInEditorOutcome(outcome)
        }
    }

    private func handleOpenInEditorOutcome(_ outcome: OpenInEditorOutcome) {
        switch outcome {
        case .open(let editor, let directory):
            EditorLaunchAdapter.open(directory, with: editor)
        case .noEditorInstalled:
            presentAlert(
                "No Editor Available",
                "Install an editor, or choose one that's installed under Preferences ▸ Editor."
            )
        case .noWorkingDirectory:
            presentAlert(
                "Couldn't Determine Working Directory",
                "Vakta couldn't find the focused pane's working directory for this session."
            )
        case .directoryMissing:
            presentAlert(
                "Directory Not Found",
                "The focused pane's working directory no longer exists on disk."
            )
        }
    }

    private func closeSwitcher() {
        switcherPanel?.orderOut(nil)
        window?.makeKeyAndOrderFront(nil)
    }
}

// MARK: - Menu-bar dropdown

extension AppDelegate: NSMenuDelegate {
    /// Rebuilt on each open so session rows and their status dots are
    /// current. Also handles the app menu's "New Session" submenu -- see
    /// its construction comment in `buildMainMenu` -- so editing/deleting a
    /// profile is reflected the next time either menu opens, not just in
    /// the (already-live, SwiftUI-driven) sidebar menu.
    func menuNeedsUpdate(_ menu: NSMenu) {
        if menu === newSessionProfilesMenu {
            menu.removeAllItems()
            for entry in ProfileMenuPlanner.entries(for: sessionStore.profiles) {
                let item = NSMenuItem(title: entry.title, action: #selector(newSessionFromProfile(_:)), keyEquivalent: "")
                item.target = self
                item.representedObject = entry.profileID
                menu.addItem(item)
            }
            return
        }
        guard menu === statusItem?.menu else { return }
        menu.removeAllItems()

        let sessions = sessionStore.sessions
        let waiting = sessionStore.agentStatus.values.filter { $0 == .attention }.count
        let summary = sessions.isEmpty
            ? "No sessions"
            : "\(sessions.count) session\(sessions.count == 1 ? "" : "s") · \(waiting) waiting"
        let header = NSMenuItem(title: summary, action: nil, keyEquivalent: "")
        header.isEnabled = false
        menu.addItem(header)
        menu.addItem(.separator())

        for session in sessions {
            let status = sessionStore.agentStatus[session.id] ?? .none
            let item = NSMenuItem(
                title: session.displayTitle,
                action: #selector(menuBarSelectSession(_:)),
                keyEquivalent: ""
            )
            item.target = self
            item.representedObject = session.id
            item.image = statusDotImage(status)
            item.state = (session.id == sessionStore.selectedID) ? .on : .off
            menu.addItem(item)
        }

        menu.addItem(.separator())
        let show = NSMenuItem(title: "Show Vakta", action: #selector(showMainWindow), keyEquivalent: "")
        show.target = self
        menu.addItem(show)
        let quit = NSMenuItem(title: "Quit Vakta", action: #selector(NSApplication.terminate(_:)), keyEquivalent: "")
        quit.target = NSApp
        menu.addItem(quit)
    }
}

// MARK: - Seamless split view

/// An `NSSplitView` that keeps a real, draggable divider (so the sidebar can
/// still be resized by dragging and collapsed via `setPosition`) but paints no
/// line, so the sidebar's vibrancy meets the opaque terminal with no visible
/// seam. Only the *drawing* is suppressed -- thickness and hit-testing are the
/// stock `.thin` behavior.
private final class SeamlessSplitView: NSSplitView {
    /// Called with the sidebar pane's width after the user finishes dragging
    /// the divider (never for programmatic `setPosition`, which doesn't route
    /// through `mouseDown` -- so there's no feedback loop with
    /// `applySidebarWidth`). `AppDelegate` decides whether to record it.
    var onDividerDragEnded: ((CGFloat) -> Void)?

    /// Like `onDividerDragEnded` but for the right-hand file sidebar (the last
    /// arranged subview), reported after a drag of the second divider. Fires
    /// for any divider drag; `AppDelegate` only records a real change.
    var onFileSidebarDragEnded: ((CGFloat) -> Void)?

    // `NSSplitView.mouseDown` runs its divider drag-tracking loop synchronously,
    // so by the time `super` returns the drag is complete and the sidebar pane's
    // frame holds the width the user let go at.
    override func mouseDown(with event: NSEvent) {
        super.mouseDown(with: event)
        if let sidebarWidth = arrangedSubviews.first?.frame.width {
            onDividerDragEnded?(sidebarWidth)
        }
        if arrangedSubviews.count >= 3, let fileWidth = arrangedSubviews.last?.frame.width {
            onFileSidebarDragEnded?(fileWidth)
        }
    }

    // A faint hairline instead of the stock heavy line: enough to separate the
    // sidebar from the same-colored terminal without a harsh black divider.
    // The top titlebar band is left unpainted so the hairline never crosses the
    // traffic lights -- when the sidebar collapses to the icon rail (narrower
    // than the traffic-light cluster) the divider otherwise cuts through them.
    override func drawDivider(in rect: NSRect) {
        let titlebarBand: CGFloat = 28 // matches SidebarView/AppDelegate inset
        // Non-flipped coords (origin bottom-left): trim the height so the top
        // band stays clear.
        var painted = rect
        painted.size.height = max(0, rect.height - titlebarBand)
        // Snap to the backing pixel grid before filling: an unaligned 1pt
        // rect gets antialiased across two pixel columns at less than full
        // alpha each, which at 8% white reads as a broken/dotted line
        // rather than a crisp hairline.
        painted = backingAlignedRect(painted, options: .alignAllEdgesNearest)
        NSColor.white.withAlphaComponent(0.08).setFill()
        painted.fill()
    }
}

// MARK: - Session switcher panel lifecycle

extension AppDelegate: NSWindowDelegate {
    /// Dismiss the switcher when it loses key focus (click elsewhere), so it
    /// behaves like a proper command palette.
    func windowDidResignKey(_ notification: Notification) {
        guard let window = notification.object as? NSWindow, window === switcherPanel else { return }
        switcherPanel?.orderOut(nil)
    }
}
